Update CodeDom.cs
On a German Windows the test failed because the message read:

c:\temp\CSSCRIPT\11612.1a78afde-4d14-4b67-a691-b716bf9a86cc.tmp(1,1): error CS0116: Ein Namespace kann nicht direkt Member, wie z.B. Felder oder Methoden, enthalten.